import numpy as np

from Initials import Simulation_Time_Setup
from Nominal_Dynamic_Model.Nominal_States_Obtainer import states_eml2o
from Nominal_Dynamic_Model.Nominal_States_Obtainer import states_elo