import matplotlib.pyplot as plt
from Estimation_Model.Executor import stdP
from Estimation_Model.Executor import t
from Estimation_Model.Executor import x_error
from Estimation_Model.Executor import visibility


std_Pk_up = 3*stdP
std_Pk_down =-3*stdP

plt.figure()
plt.plot(t, x_error[:, 0], color='red', label='x')
plt.plot(t, x_error[:, 1], color='blue', label='y')
plt.plot(t, x_error[:, 2], color='green', label='z')
plt.plot(t, std_Pk_up[:, 0], color='orange', linestyle='--' , label='3$\sigma_{x}$')
plt.plot(t, std_Pk_down[:, 0], color='orange', linestyle='--')
plt.plot(t, std_Pk_up[:, 1], color='cyan', linestyle='--', label='3$\sigma_{y}$')
plt.plot(t, std_Pk_down[:, 1], color='cyan', linestyle='--')
plt.plot(t, std_Pk_up[:, 2], color='yellow', linestyle='--', label='3$\sigma_{z}$')
plt.plot(t, std_Pk_down[:, 2], color='yellow', linestyle='--')
plt.legend()
plt.xlim(0, 10)
plt.grid(True, which="both", ls="-")
plt.xlabel('Time since epoch [days]')
plt.ylabel('Estimated position error [m]')
plt.title('EML2 position error')

plt.figure()
plt.plot(t, x_error[:, 3], color='red', label='$\dot{x}$')
plt.plot(t, x_error[:, 4], color='blue', label='$\dot{y}$')
plt.plot(t, x_error[:, 5], color='green', label='$\dot{z}$')
plt.plot(t, std_Pk_up[:, 3], color='orange', linestyle='--', label='3$\sigma_{\dot{x}}$')
plt.plot(t, std_Pk_down[:, 3], color='orange', linestyle='--')
plt.plot(t, std_Pk_up[:, 4], color='cyan', linestyle='--', label='3$\sigma_{\dot{y}}$')
plt.plot(t, std_Pk_down[:, 4], color='cyan', linestyle='--')
plt.plot(t, std_Pk_up[:, 5], color='yellow', linestyle='--', label='3$\sigma_{\dot{z}}$')
plt.plot(t, std_Pk_down[:, 5], color='yellow', linestyle='--')
plt.legend()
plt.xlim(0, 10)
plt.grid(True, which="both", ls="-")
plt.xlabel('Time since epoch [days]')
plt.ylabel('Estimated velocity error [m/s]')
plt.title('EML2 velocity error')

plt.figure()
plt.plot(t, x_error[:, 6], color='red', label='x')
plt.plot(t, x_error[:, 7], color='blue', label='y')
plt.plot(t, x_error[:, 8], color='green', label='z')
plt.plot(t, std_Pk_up[:, 6], color='orange', linestyle='--', label='3$\sigma_{x}$')
plt.plot(t, std_Pk_down[:, 6], color='orange', linestyle='--')
plt.plot(t, std_Pk_up[:, 7], color='cyan', linestyle='--', label='3$\sigma_{y}$')
plt.plot(t, std_Pk_down[:, 7], color='cyan', linestyle='--')
plt.plot(t, std_Pk_up[:, 8], color='yellow', linestyle='--', label='3$\sigma_{z}$')
plt.plot(t, std_Pk_down[:, 8], color='yellow', linestyle='--')
plt.legend()
plt.xlim(0, 10)
plt.grid(True, which="both", ls="-")
plt.xlabel('Time since epoch [days]')
plt.ylabel('Estimated position error [m]')
plt.title('ELO position error')

plt.figure()
plt.plot(t, x_error[:, 9], color='red', label='$\dot{x}$')
plt.plot(t, x_error[:, 10], color='blue', label='$\dot{y}$')
plt.plot(t, x_error[:, 11], color='green', label='$\dot{z}$')
plt.plot(t, std_Pk_up[:, 9], color='orange', linestyle='--', label='3$\sigma_{\dot{x}}$')
plt.plot(t, std_Pk_down[:, 9], color='orange', linestyle='--')
plt.plot(t, std_Pk_up[:, 10], color='cyan', linestyle='--', label='3$\sigma_{\dot{y}}$')
plt.plot(t, std_Pk_down[:, 10], color='cyan', linestyle='--')
plt.plot(t, std_Pk_up[:, 11], color='yellow', linestyle='--', label='3$\sigma_{\dot{z}}$')
plt.plot(t, std_Pk_down[:, 11], color='yellow', linestyle='--')
plt.legend()
plt.xlim(0, 10)
plt.grid(True, which="both", ls="-")
plt.xlabel('Time since epoch [days]')
plt.ylabel('Estimated velocity error [m/s]')
plt.title('ELO velocity error')

plt.figure()
plt.plot(t, visibility)
plt.xlabel('Time [days]')
plt.ylabel('Visibility [0:No, 1:Yes]')
plt.title('Visbility between the satellites')
plt.show()

